// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYCNS0pZeQqgDxElZZA0jR2Ev6BuNeXs0',
    appId: '1:500950660538:web:2ed8489a3b422dce681983',
    messagingSenderId: '500950660538',
    projectId: 'crazy-dorm',
    authDomain: 'crazy-dorm.firebaseapp.com',
    storageBucket: 'crazy-dorm.firebasestorage.app',
    measurementId: 'G-L46HVHPV05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM53fjwSm60J3MJZDPNftzdtFOEPLYAOk',
    appId: '1:500950660538:android:e7914effeacbe8fb681983',
    messagingSenderId: '500950660538',
    projectId: 'crazy-dorm',
    storageBucket: 'crazy-dorm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRO2pOUe9GbD4Z0VPlRuaO4nwdAQUPd0c',
    appId: '1:500950660538:ios:3ac2a55bb9f75c8d681983',
    messagingSenderId: '500950660538',
    projectId: 'crazy-dorm',
    storageBucket: 'crazy-dorm.firebasestorage.app',
    iosBundleId: 'com.example.crazyDorm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRO2pOUe9GbD4Z0VPlRuaO4nwdAQUPd0c',
    appId: '1:500950660538:ios:3ac2a55bb9f75c8d681983',
    messagingSenderId: '500950660538',
    projectId: 'crazy-dorm',
    storageBucket: 'crazy-dorm.firebasestorage.app',
    iosBundleId: 'com.example.crazyDorm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYCNS0pZeQqgDxElZZA0jR2Ev6BuNeXs0',
    appId: '1:500950660538:web:696e80b9da158b4e681983',
    messagingSenderId: '500950660538',
    projectId: 'crazy-dorm',
    authDomain: 'crazy-dorm.firebaseapp.com',
    storageBucket: 'crazy-dorm.firebasestorage.app',
    measurementId: 'G-39G48XY9KM',
  );

}